// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxtSG3cSXvSCXjFyLPZFs8waQMY8iTlI',
    appId: '1:288279982853:web:3d57f383e489faf344bd6c',
    messagingSenderId: '288279982853',
    projectId: 'carebridge-860a9',
    authDomain: 'carebridge-860a9.firebaseapp.com',
    databaseURL: 'https://carebridge-860a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-860a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIZNnSiOlL6At9A9T7vtI31UO2PkS-WbA',
    appId: '1:288279982853:android:b36ee260aaad08b944bd6c',
    messagingSenderId: '288279982853',
    projectId: 'carebridge-860a9',
    databaseURL: 'https://carebridge-860a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-860a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMBjMd6-b_U1o16kuZaF67MNSl4SY3mvA',
    appId: '1:288279982853:ios:140d3384dd14f75d44bd6c',
    messagingSenderId: '288279982853',
    projectId: 'carebridge-860a9',
    databaseURL: 'https://carebridge-860a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-860a9.appspot.com',
    iosClientId: '288279982853-qqf4g303o652hjrh2826uap7di9tmvvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.careBridgeUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMBjMd6-b_U1o16kuZaF67MNSl4SY3mvA',
    appId: '1:288279982853:ios:140d3384dd14f75d44bd6c',
    messagingSenderId: '288279982853',
    projectId: 'carebridge-860a9',
    databaseURL: 'https://carebridge-860a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-860a9.appspot.com',
    iosClientId: '288279982853-qqf4g303o652hjrh2826uap7di9tmvvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.careBridgeUi',
  );
}
